/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "telescope": [
        {
            "name": "view",
            "required": false
        }
    ],
    "home": [],
    "admin.home": [],
    "admin.login": [],
    "admin.": [],
    "admin.logout": [],
    "admin.system.config.main": [],
    "admin.system.config.admin": [],
    "admin.system.permission.index": [],
    "admin.system.permission.list": [],
    "admin.system.permission.lazyData": [],
    "admin.system.permission.edit": [],
    "admin.system.permission.detail": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
