/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
    interface RouteList {
        telescope: [
            {
                name: 'view'
                required: false
            },
        ]
        home: []
        'admin.home': []
        'admin.login': []
        'storage.local': [
            {
                name: 'path'
                required: true
            },
        ]
    }
}
export {}
